version: "3.9"
services:
  frontend:
    build: ./react-frontend
    image: "dockercompose/frontend:0.0.6"  # or 0.0.17 #docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' springboot
    container_name: react      #127 image 1 # image public ip # image3 localhost # image4 container name
    stdin_open: true
    environment:
      EMPLOYEE_API_BASE_URL: "http://0.0.0.0:8080/api/v1/employees"
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
      - springboot

  springboot:
    image: pavanvere/spring:0.0.10
    container_name: springboot
    environment:
      MONGO_URL: mongodb://mongodb:27017/EmployeeDB
    ports:
    - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
    - "27017:27017"