version: "3.9"
services:
  frontend:
    image: pavanvere/frontend:latest
    container_name: frontend
    ports:
      - "3000:8080"

  springboot:
    image: pavanvere/springboot:latest
    container_name: springboot
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    container_name: mongodb