version: "3.9"
services:
  frontend:
    image: pavanvere/frontend:latest
    container_name: frontend
    restart: on-failure
    ports:
      - "3000:3000"

  springboot:
    image: pavanvere/springboot:latest
    container_name: springboot
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    container_name: mongodb
    ports:
    - "27017:27017"